Add hero section
SOunit/ciccc_real_estate pull request #2
Opened 2022-01-20 04:03 UTC by Kousei0422

2022-01-20 22:59 UTC, SOunit requested changes
修正があるので、対応をお願いします。

2022-01-20 22:59 UTC, SOunit commented on index.html
> +    <div class = "hero">
先にプルをしてください。
masterブランチでプルして、masterブランチの変更を、作業中のブランチにマージしてから、プルリクをお願いします。

2022-01-20 23:01 UTC, SOunit commented on index.html
> +    <div class = "hero">
でないと、きょうこさんの変更の差分を上書きしてしまうので。

2022-01-21 00:26 UTC, Kousei0422 commented
created another pull-request. close.

2022-01-21 00:26 UTC, closed without merging